# ROI de uma Imagem:


Um conceito importante em processamento de imagens é a **Região de Interesse**. Entende-se como Região de Interesse (ROI - "Region Of Interest" ou AOI - "Area Of Interest") a região obtida de maneira automática ou a partir da interação de um usuário onde o processamento estará totalmente concentrado. 

### Objetivos:

1. Obter um ROI de uma imagem a partir da área selecionada pelo mouse



In [1]:
# Bibliotecas
import cv2
import numpy as np

# Imagem teste
image = cv2.imread('lena.png')
image_to_show = np.copy(image)

# Estados iniciais do mouse
cropping = False
x_init, y_init, top_left_pt, bottom_right_pt = 0, 0, 0, 0


def roi(event, x, y, flags, param):
    global image_to_show, x_init, y_init, top_left_pt, bottom_right_pt, cropping

    if event == cv2.EVENT_LBUTTONDOWN:
        cropping = True
        x_init, y_init = x, y
        image_to_show = np.copy(image)
        print(f'Ponto inicial em X {x_init}')
        print(f'Ponto inicial em Y {y_init}')

    elif event == cv2.EVENT_MOUSEMOVE:
        if cropping == True:
            image_to_show = np.copy(image)
            cv2.rectangle(image_to_show, (x_init, y_init),
                          (x, y), (0, 255, 0), 1)

    elif event == cv2.EVENT_LBUTTONUP:
        cropping = False
        top_left_pt, bottom_right_pt = x, y
        print(f'Ponto superior {top_left_pt}')
        print(f'Ponto inferior {bottom_right_pt}')


cv2.namedWindow('image')
cv2.setMouseCallback('image', roi)

while True:

    cv2.imshow('image', image_to_show)
    k = cv2.waitKey(1)

    if k == ord('c'):
        if y_init > bottom_right_pt:
            y_init, bottom_right_pt = bottom_right_pt, y_init
        if x_init > top_left_pt:
            x_init, top_left_pt = top_left_pt, x_init

        if bottom_right_pt - y_init > 1 and top_left_pt - x_init > 0:
            image = image[y_init:bottom_right_pt, x_init:top_left_pt]
            print(image)
            image_to_show = np.copy(image)

    if k == ord('s'):
        cv2.imwrite('teste.jpg', image_to_show)

    if cv2.waitKey(1) == ord('q'):
        break

cv2.destroyAllWindows()


Ponto inicial em X 202
Ponto inicial em Y 175
Ponto superior 379
Ponto inferior 381
[[[108  91 189]
  [121 107 195]
  [123 123 208]
  ...
  [189 208 235]
  [190 206 233]
  [157 175 222]]

 [[110  99 201]
  [107 108 210]
  [128 122 212]
  ...
  [172 197 231]
  [139 180 227]
  [145 155 213]]

 [[116 112 207]
  [121 120 208]
  [111 109 207]
  ...
  [134 156 218]
  [128 144 212]
  [131 140 206]]

 ...

 [[ 64  23  97]
  [ 57  19  95]
  [ 59  28 103]
  ...
  [125 111 176]
  [150 156 211]
  [156 161 217]]

 [[ 58  20  90]
  [ 61  18  94]
  [ 61  19  99]
  ...
  [127 107 177]
  [145 160 215]
  [161 162 216]]

 [[ 68  22  89]
  [ 67  17  88]
  [ 65  23  97]
  ...
  [124 113 188]
  [145 157 216]
  [145 160 214]]]
